Changed oxygen tank from linear progression to exponential.
GTNewHorizons/Galacticraft pull request #20
Opened 2021-03-26 18:22 UTC by johnch18

I changed the oxygen tank capacities to grow by 60% per tier. This nerfs earlier tier tanks and buffs later tier ones. I think only increasing capacity by 1000L a tier doesn't make sense given the growing material cost per tier.

2021-03-26 18:33 UTC, glowredman commented
I think thos would be a good change, why did you choose 60% though?

2021-03-26 18:39 UTC, johnch18 commented
I wanted a number greater than 1.5 but below 2, 1.6 seemed about right. I'm not set on it by any means.

2021-03-26 18:47 UTC, glowredman commented
1.5 would mean a max capacity of about 5000 (5060) like now but I'm not opposed of raising the max capacity either.

2021-03-26 18:54 UTC, glowredman commented
I linked your PR on Discord, maxbe someone else will have a look aswell.

2021-03-26 19:05 UTC, Dream-Master commented
The idea is good but i am not sure about the values.

2021-03-26 19:13 UTC, johnch18 commented
![image](https://user-images.githubusercontent.com/42650497/112681974-0d26f580-8e35-11eb-8607-3b31da7e93ac.png)
I put a spreadsheet with different values for the % gain, and the current method on the left.

2021-03-26 19:17 UTC, Prometheus0000 commented
Is it 1L/s consumption?

2021-03-26 19:26 UTC, johnch18 commented
I believe so, though don't quote me

2021-03-31 09:52 UTC, Glease commented
1 per 9 in game ticks.

2021-03-31 15:52 UTC, Dream-Master commented
@johnch18 @glowredman @Glease @Prometheus0000 so what values are good. Can we make a final decission and set the values ?

2021-03-31 16:02 UTC, johnch18 commented
Well, using the 1L/9T figure and a factor of 2, the max tier would last 2 hours, the next tier 1 hour, and so on. Plus, it's a nice round number. My vote is for 2x.

2021-03-31 16:06 UTC, glowredman commented
I find that a bit much honestly. It would mean that with two tanks you can survive for 4h with two tanks. I think 90mins per tank would be more balanced -> 1.8x

2021-03-31 19:12 UTC, Prometheus0000 commented
Should you really have to worry about oxygen when you can make them? Don't they take a fusion metal? Not to mention I doubt you're sticking around longer than to slap down a MBM miner (or move it) and then leave.

2021-03-31 20:14 UTC, johnch18 commented
It's inconvenient to micromanage oxygen especially when you aren't thinking about it. This is just a QoL change for players at later tiers.

2021-04-03 04:30 UTC, johnch18 commented
Anything I can change to make this worthwhile or should I just close it?

2021-04-03 11:13 UTC, glowredman commented
No. I'd say you change it to 2x and if it's totally unbalaced (which I don't think) we'll change it later.

2021-04-05 20:04 UTC, glowredman commented
Your comment (`// 1000, 1600, 2600, 4100, ...`) is not correct anymore, otherwise looks good 👍

2021-04-06 08:51 UTC, Glease requested changes

2021-04-06 08:51 UTC, Glease commented on src/main/java/micdoodle8/mods/galacticraft/core/items/ItemOxygenTank.java
> +	// 1000, 1600, 2600, 4100, ...
Wrong as glowredman has stated

2021-04-06 12:08 UTC, johnch18 commented on src/main/java/micdoodle8/mods/galacticraft/core/items/ItemOxygenTank.java
> +	// 1000, 1600, 2600, 4100, ...
Yes honey...

2021-04-06 12:26 UTC, Glease approved these changes

2021-04-06 13:32 UTC, merged