Remove circular dependency with GalaxySpace
GTNewHorizons/Galacticraft pull request #21
Opened 2021-04-04 23:05 UTC by glowredman

- Updated Gradle to 5.6.4
- Changed to custom ForgeGradle version
- Updated dependencies
- Version variables in Constants.java and mcmod.info automatically now update to the version defined in build.gradle when building
- Removed hard-dependency on GalaxySpace (and moved the GUI assets for the Moon Buggy, Cargo Rocket and Astro Miner from GalaxySpace)

2021-04-05 02:45 UTC, bartimaeusnek requested changes
Needs some rework.

- [ ] Youre missing the gradle wrapper file.
- [ ] Also im not sure if all dependancies are resolveable.
- [ ] Asset Prefixes should be done as constants
- [ ] This does not resolve circular reference to GS, simply because it relys on GS items in any case.

2021-04-05 02:45 UTC, bartimaeusnek commented on build.gradle
> +        name "CurseForge Maven"
Can only be used with an api token

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/client/gui/container/GuiSchematicBuggy.java
> +    private static final ResourceLocation buggyBenchTexture = new ResourceLocation("galacticraftcore", "textures/gui/schematic_rocket_GS1_Buggy.png");
This should be a constant

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/inventory/SlotBuggyBench.java
> +            return itemStack.getItem() == GameRegistry.findItem("GalaxySpace", "item.RocketControlComputer") && itemStack.getItemDamage() == 100;
This still is a circular dependancy. It should be wrapped in a:
```
if (GalaxySpaceLoaded)
    GalaxySpaceItem
else
    Replacement
 ```

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/nei/BuggyRecipeHandler.java
> +    private static final ResourceLocation buggyGuiTexture = new ResourceLocation("galacticraftcore", "textures/gui/schematic_rocket_GS1_Buggy.png");
Same asset constant as above

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/nei/BuggyRecipeHandler.java
> +        return "galacticraftcore:textures/gui/schematic_rocket_GS1_Buggy.png";
Same asset constant as above

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/nei/NEIGalacticraftConfig.java
> +        input.put(3, new PositionedStack(GT_ModHandler.getModItem("GalaxySpace", "item.RocketControlComputer", 1, 100), 62 - x, 73 - y));
Same circular problem as above, needs to be wrapped

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/recipe/RecipeManagerGC.java
> +        input.put(3, GT_ModHandler.getModItem("GalaxySpace", "item.RocketControlComputer", 1, 100));
s.o.

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/AsteroidsModule.java
> +        input.put(18, GT_ModHandler.getModItem("GalaxySpace", "item.RocketControlComputer", 1, 102));
s.o.

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/gui/GuiSchematicAstroMiner.java
> +    public static final ResourceLocation schematicTexture = new ResourceLocation("galacticraftasteroids", "textures/gui/schematic_rocket_GS1_Miner.png");
s.o.

2021-04-05 02:45 UTC, bartimaeusnek commented on src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java
> +@Mod(modid = Constants.MOD_ID_CORE, name = GalacticraftCore.NAME, version = Constants.VERSION, acceptedMinecraftVersions = "[1.7.2],[1.7.10]", useMetadata = true, dependencies = "required-after:Forge
The "required-before:GalaxySpace;" part should be kept, since it clearifies load order.

2021-04-05 14:36 UTC, glowredman commented
The gradle wrapper jar [still exists](https://github.com/GTNewHorizons/Galacticraft/blob/remove-circular-dependency/gradle/wrapper/gradle-wrapper.jar), it is just not as large as prior to version 5.6.4. The CurseForge Maven was introduced by @mitchej123 and caused no problems in the past. I could import and build the project without problems.

2021-04-18 19:55 UTC, Dream-Master commented
@bartimaeusnek merge ?

2021-05-12 16:02 UTC, merged